# Generated by Django 4.0.5 on 2022-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_alter_blog_blog_image_alter_blog_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
